export const ERROR_MESSAGE = {
  AUTH_ERROR: 'AUTH_ERROR',
  DB_ERROR: 'DB_ERROR',
  RESPONSE_ERROR: 'RESPONSE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  USER_DATA_ERROR: 'USER_DATA_ERROR',
}

export const HTTP_STATUS_CODE = {
  200: 200,
  401: 401,
  500: 500,
  422: 422,
}
