name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr lint
      - run: nr typecheck

  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        node: [lts/*]
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr build

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          project_id: ${{ secrets.NEON_PROJ_ID }}
          branch_name: testing/${{ matrix.platform }}/${{ steps.branch-name.outputs.current_branch }}
          username: koadb_owner
          database: koadb
          api_key: ${{ secrets.NEON_API_KEY }}

      - run: nr test
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}

      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJ_ID }}
          branch: testing/${{ matrix.platform }}/${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
