name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr lint
      - run: nr typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          project_id: ${{ secrets.NEON_PROJ_ID }}
          parent: main
          database: koadb
          branch_name: testing
          username: koadb_owner
          api_key: ${{ secrets.NEON_API_KEY }}

      - run: bun i -g @antfu/ni
      - run: nci
      - run: nr build
      - run: nr test
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}

      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJ_ID }}
          branch: testing
          api_key: ${{ secrets.NEON_API_KEY }}
