name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm i -g @antfu/ni
      - run: nci
      - run: nr lint
      - run: nr typecheck

  test:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        node: [lts/*]
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres

      - run: npm i -g @antfu/ni
      - run: nci
      - run: nr build

      - name: DB Initialize
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
        run: |
          createuser starter
          createdb --owner starter koadb
          psql -c "ALTER USER starter WITH PASSWORD 'starter'"

      - name: DB Checking
        env:
          PGSERVICE: ${{ steps.postgres.outputs.service-name }}
        run: |
          psql ${{ steps.postgres.outputs.connection-uri }} -c "SELECT 1"
          psql service=${{ steps.postgres.outputs.service-name }} -c "SELECT 1"
          psql -c "SELECT 1"

      - run: nr test
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
